### ISSUE TITLE
Token Autentication and Pull into Bundles folder 

### ISSUE THREAD

**Issue by watarutetsuya** [netsuite-upload-org/netsuite-upload#16]
Hello, I want to know if you have thought of including token authentication and a configuration to upload to the bundle folder.

**Comment by silverl** [comment]
Both issues are resolved in the new version. I've greatly improved the README.md which should help make setup more clear.

Note that reading/writing to SuiteBundles requires that your Role have the Setup…SuiteBundles:Full permission. You'll need to change the local settings.json to read/write to SuiteBundles instead of SuiteScripts. See the README.md.

I've un-published the original extension and re-published it under my own credentials. Please uninstall old and install new. The name is the same, `netsuite-upload`.

https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload
