### ISSUE TITLE
Directory Push

### ISSUE THREAD

**Issue by Godrules500** [netsuite-upload-org/netsuite-upload#17]
I don't see where this is currently possible, so if it is I apologize, but are there any plans to add the ability to push an entire directory?

**Comment by silverl** [comment]
It's currently not supported. The original author did not add it. You can upload a single file in a new folder, and it will create the folder correctly in NetSuite. But there's no batch upload at this time.

**Comment by email2poornileesa** [comment]
Hi silverl,
I used vscodeExtensionRestlet.js and added to NS account. I always get error as please update latest version   of vscodeExtensionRestlet.js when i try to push file to NS account.

**Comment by silverl** [comment]
@email2poornileesa that's a separate issue, so I have created a separate GitHub Issue for it: #25

**Comment by Cmacu** [comment]
Directory Push (and possibly excluding .ts files) would be awesome feature for TypeScript developers. Right now I have to switch editor focus in order to push the correct file to NetSuite via shortcut.
Another useful feature would be an option to save the file before pushing it.
I will look into it this weekend and possibly create PR if I figure it out.

**Comment by Cmacu** [comment]
Here is the [PR](https://github.com/netsuite-upload-org/netsuite-upload/pull/35)

**Comment by silverl** [comment]
Now live with v1.2.3!
