### ISSUE TITLE
Compare file error (Windows)

### ISSUE THREAD

**Issue by JosueIsaiSmg** [netsuite-upload-org/netsuite-upload#20]
![image](https://user-images.githubusercontent.com/22876037/52505416-0daa9680-2bb1-11e9-9ba2-3b17df394082.png)
settings json: "netSuiteUpload.tempFolder": "C:\\SuiteScript"

**Comment by silverl** [comment]
Does `helloworld.js` exist in the root of your SuiteScripts folder?

Does C:\\SuiteScript folder exist, and do you have permissions to read/write?

**Comment by JosueIsaiSmg** [comment]
Yes it exist, and I have Full access on that folder to Users and Administrators.
![image](https://user-images.githubusercontent.com/22876037/52515694-b1fa0080-2be4-11e9-9c1d-f97284fbe171.png)
![image](https://user-images.githubusercontent.com/22876037/52515713-d7870a00-2be4-11e9-91f3-5acbc1e1cc82.png)

**Comment by silverl** [comment]
What version of the Extension are you running? If you're on less than `1.1.2` please uninstall that extension and reinstall `netsuite-upload` from the extensions marketplace.

The rest of this assumes you're on the latest version `1.1.2`.

I took at look at the source code. At that point in the code, it's successfully pulled down the file and written it to the temp folder. There's error handling around downloading the file and writing it to the file system. 

I'm on Windows (looks like you are too, or we wouldn't be talking about a C: drive).

I created a C:\SuiteScripts folder and specified it in my settings.json as `C:/SuiteScripts`.  `c:\\SuiteScripts` also works (with two backslashes - escaping backslashes is required because this is  JSON).

I'm not having any trouble comparing files.

Do you see the file helloworld.preview.js in your local C:\SuiteScripts folder?

Can you please share a screenshot of the `netSuiteUpload.tempFolder` setting in your `settings.json`?

Thanks.

**Comment by JosueIsaiSmg** [comment]
Im using the lastet version 1.1.2. 
I see the problem, it was the wrong backslash C:\SuiteScripts
![image](https://user-images.githubusercontent.com/22876037/52541262-94e63e80-2d58-11e9-8c7a-0e58ab053241.png)
Now it works! 
I'm sorry for my silly mistake

**Comment by silverl** [comment]
Glad you're up and running.
