### ISSUE TITLE
Warning to update to latest version of vscodeExtensionRestlet.js

### ISSUE THREAD

**Issue by silverl** [netsuite-upload-org/netsuite-upload#25]
Hi silverl,
I used vscodeExtensionRestlet.js and added to NS account. I always get error as please update latest version   of vscodeExtensionRestlet.js when i try to push file to NS account.

_Originally posted by @email2poornileesa in https://github.com/netsuite-upload-org/netsuite-upload/issues/17#issuecomment-482526375_

**Comment by silverl** [comment]
@email2poornileesa,

I believe this error is hiding the real issue, I've seen it before. It's likely a connection or authentication problem.

Are you trying NLAuth or OAuth?

**Comment by email2poornileesa** [comment]
hi Silverl,
I am using NLAuth. I fixed connection issue after fixing connection I get this error for this file to be latest version

**Comment by silverl** [comment]
Is this the first time you're trying to use this VS Code extension? Or have you used it before and you are now upgrading ?

In general, the more details you can provide about what you've tried and haven't tried, the more I can help you. Please be as detailed as you can.

I'd ask you to please go back through the instructions in the README, line by line. Please ensure you've set up the scriptlet with the proper permissions, and that your user also has the necessary permissions listed there.

If you're a developer and are familiar with Postman and calling NetSuite RESTlets from Postman, you can use Postman to troubleshoot. You could also do this with cURL, wget or any other API calling tool.

In Postman
- Set up a GET request to the deployed RESTlet's URL.
- Add two Headers:
-- Authorization: Use your NLAuth connection string
-- Content-Type: application/json
- Add a Param (you should already have two, `script` and `deploy` params, which Postman will pull from the querystring of the RESTlet URL)
-- type: version

When you submit this request, you should receive a JSON payload which contains something like:

```
{
    "restletVersion": "1.0.2"
}
```

**Comment by AndersonFirmino** [comment]
I have tried every possible alternative. And this bug happened to me too.
I tried with OAuthToken and by NLAuth. And both generate this error. Every time I reviewed the README.md document each line.
I believe the logs should be more explanatory as they do not give a clue what might be wrong. In some environments it works and in other environments it does not work. With the same role set up.

**Comment by grugknuckle** [comment]
When I try this through Postman, I get

```js
{
    "error": {
        "code": "USER_ERROR",
        "message": "Could not determine customer compid"
    }
}
```

I'm pretty sure my NL_Auth string is correct.

**Comment by silverl** [comment]
Are you able to test with a user having the Administrator role? If it works with an Administrator, but not with other users, then we'll need to figure out what role or permission is lacking in the non-admin role.

**Comment by silverl** [comment]
On that error, `Could not determine customer compid`, I googled and found this: https://stackoverflow.com/questions/34932602/could-not-determine-customer-compid-user-error-in-netsuite-sandbox

**Comment by silverl** [comment]
Here are some other leads on that error: https://www.techfino.com/blog/netsuite-token-authentication

**Comment by grugknuckle** [comment]
I removed spaces from my NL Auth connection string. That didn't fix it.
I am a NetSuite Administrator and using my own credentials to log in.

One thing is that our organization has mandatory 2-factor authentication set up for administrators. I wonder if using NL Auth with an admin use is failing because 2fa shenanigans?

**Comment by grugknuckle** [comment]
Update ... When I switch my settings in VSCode over to token authentication and try to push a script, VSCode gives me the error

```
ERROR uploading file. | You might need to update the vscodeExtensionRestlet.js RESTlet in NetSuite to the latest version. | Use Help…Toggle Developer Tools and choose the Console tab for a better formatted error message.
```

**Comment by silverl** [comment]
What do you see when you follow the instructions to open Developer Tools and look in the Console tab, like it says?

**Comment by grugknuckle** [comment]
![gitpic](https://user-images.githubusercontent.com/15350004/65056988-e0407b00-d93f-11e9-8874-24bf0d8515b8.jpg)

The image above is when I try to use a token. It says, 

ERROR uploading file. | You might need to update the vscodeExtensionRestlet.js RESTlet in NetSuite to the latest version. | Use Help…Toggle Developer Tools and choose the Console tab for a better formatted error message.

**Comment by silverl** [comment]
I would guess nlauth definitely won't work with 2FA. But you'd expect to see an appropriate exception returned from the API in that case.

For token auth, it has got to be a mistake in setup. A token would not be subject to 2FA.

That error about needing to update the RESTlet is what happens due to bad error handling whenever the client can't authenticate or connect. The message is definitely not helpful, but I haven't yet figured out how to trap every exception around connecting since adopting this code base from the creator earlier this year, I'm sorry.

**Comment by grugknuckle** [comment]
@silverl First of all, thanks for working with me on this and for responding all day. I know how annoying it can be to maintain other people's repositories. Second, I was doing some research on this. And it seems there is a consensus on the internets that NetSuite's error codes are pretty unhelpful.

I'm starting to wonder if I've properly deployed the vscodeExtensionRestlet.js script. Let me explain ... When I use the NL Auth method, the error I got was a 403 Unauthorized. As you pointed out, that's probably because of 2FA. When I use the token, I get the "Error uploading file. Update restlet ..." error. Well I checked the version manually by reading the version of that file straight out of the NetSuite file cabinet and it is version 1.0.2 - so that's not the problem. However, when I look at the scripts execution log in NetSuite, that log is blank. Now, maybe there aren't any logs being made by the RESTlet. But perhaps when I pushed the file from vsCode, I couldn't actually reach the restlet - which could happen if I hadn't properly created a deployment record for the script. 

When I created the deployment record, I followed simply what was in the README.

* Create a new Script Deployment for this Script. Note the URL.

But that's not very specific. Are there more details to this deployment that I"m missing?

**Comment by alejndr** [comment]
> 
> When I created the deployment record, I followed simply what was in the README.
> 
> * Create a new Script Deployment for this Script. Note the URL.
> 
> But that's not very specific. Are there more details to this deployment that I"m missing?

In the script deployment of the restlet there are two URLs, **URL** and **External URL**, you have to copy the **External URL** and paste it in the settings.json of your workspace like this:

```
// Script Deployment URL for the deployed vscodeExtensionRestlet.js
"netSuiteUpload.restlet": <External URL>
```

**Comment by grugknuckle** [comment]
> In the script deployment of the restlet there are two URLs, **URL** and **External URL**, you have to copy the **External URL** and paste it in the settings.json of your workspace like this:
> 
> ```
> // Script Deployment URL for the deployed vscodeExtensionRestlet.js
> "netSuiteUpload.restlet": <External URL>
> ```

Yep. I've got my external URL in settings.json as

https://<my-netsuite-account-id>.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=865&deploy=1

**Comment by grugknuckle** [comment]
@alejndr @silverl OK guys ... thank you for your help. The problem I had was with my NetSuite Sandbox Account ID. I was using XXXXXXX-SB1 instead of XXXXXXX_SB1 (dash instead of underscore).

Sorry for wasting your time, but I really do appreciate your help.

**Comment by silverl** [comment]
Glad you figured it out. I'll close this issue.
